"""Hypothesis-related data models."""

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class HypothesisStatus(str, Enum):
    """Status of a hypothesis in the pipeline."""

    GENERATED = "generated"
    UNDER_REVIEW = "under_review"
    REVIEWED = "reviewed"
    RANKED = "ranked"
    EVOLVED = "evolved"
    SELECTED = "selected"
    REJECTED = "rejected"


class HypothesisType(str, Enum):
    """Type of hypothesis."""

    CAUSAL = "causal"  # X causes Y
    CORRELATIONAL = "correlational"  # X is related to Y
    METHODOLOGICAL = "methodological"  # New method/approach
    COMPARATIVE = "comparative"  # A is better than B for task C
    EXPLORATORY = "exploratory"  # Investigating unknown patterns
    PREDICTIVE = "predictive"  # X can predict Y


class Hypothesis(BaseModel):
    """A scientific hypothesis generated by the co-scientist."""

    id: str = Field(default_factory=lambda: f"hyp_{datetime.now().strftime('%Y%m%d_%H%M%S_%f')}")
    goal_id: str = Field(..., description="ID of the associated research goal")
    title: str = Field(..., description="Short title for the hypothesis")
    statement: str = Field(..., description="The full hypothesis statement")
    hypothesis_type: HypothesisType = Field(
        default=HypothesisType.EXPLORATORY,
        description="Type of hypothesis"
    )
    rationale: str = Field(
        default="",
        description="Justification/reasoning behind the hypothesis"
    )
    assumptions: list[str] = Field(
        default_factory=list,
        description="Key assumptions underlying the hypothesis"
    )
    variables: dict[str, str] = Field(
        default_factory=dict,
        description="Key variables (independent, dependent, control)"
    )
    testability: str = Field(
        default="",
        description="How this hypothesis can be tested"
    )
    supporting_references: list[str] = Field(
        default_factory=list,
        description="Reference IDs that support this hypothesis"
    )
    status: HypothesisStatus = Field(
        default=HypothesisStatus.GENERATED,
        description="Current status in the pipeline"
    )
    elo_score: float = Field(
        default=1000.0,
        description="Elo rating score from tournament ranking"
    )
    generation_iteration: int = Field(
        default=1,
        description="Which iteration this hypothesis was generated in"
    )
    parent_hypothesis_id: Optional[str] = Field(
        default=None,
        description="ID of parent hypothesis if this is an evolved version"
    )
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: datetime = Field(default_factory=datetime.now)

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "title": "Urban Heat Island Detection via Thermal-NDVI Fusion",
                "statement": "Urban heat islands can be more accurately detected by combining "
                           "nighttime thermal IR data with NDVI, as this isolates anthropogenic "
                           "heat signals by accounting for vegetation cooling effects.",
                "hypothesis_type": "methodological",
                "rationale": "Vegetation has a known cooling effect on surface temperature. "
                           "By incorporating NDVI, we can distinguish between areas that are "
                           "hot due to lack of vegetation versus true urban heat effects.",
                "assumptions": [
                    "NDVI accurately represents vegetation density",
                    "Thermal data quality is consistent across the study area"
                ],
                "variables": {
                    "independent": "NDVI, Thermal IR surface temperature",
                    "dependent": "Urban heat island intensity",
                    "control": "Elevation, proximity to water bodies"
                }
            }
        }
    )


class ReviewCriterion(str, Enum):
    """Criteria for hypothesis review."""

    LOGICAL_CONSISTENCY = "logical_consistency"
    NOVELTY = "novelty"
    TESTABILITY = "testability"
    SCIENTIFIC_SOUNDNESS = "scientific_soundness"
    FEASIBILITY = "feasibility"
    RELEVANCE = "relevance"
    CLARITY = "clarity"


class HypothesisReview(BaseModel):
    """Review/critique of a hypothesis by the Reflection agent."""

    id: str = Field(default_factory=lambda: f"review_{datetime.now().strftime('%Y%m%d_%H%M%S_%f')}")
    hypothesis_id: str = Field(..., description="ID of the reviewed hypothesis")
    reviewer_type: str = Field(
        default="reflection_agent",
        description="Type of reviewer (initial, full, human)"
    )

    # Scores for each criterion (0-1 scale)
    scores: dict[str, float] = Field(
        default_factory=lambda: {
            "logical_consistency": 0.0,
            "novelty": 0.0,
            "testability": 0.0,
            "scientific_soundness": 0.0,
            "feasibility": 0.0,
            "relevance": 0.0,
            "clarity": 0.0,
        },
        description="Scores for each review criterion"
    )

    overall_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Overall quality score"
    )

    strengths: list[str] = Field(
        default_factory=list,
        description="Identified strengths of the hypothesis"
    )
    weaknesses: list[str] = Field(
        default_factory=list,
        description="Identified weaknesses or concerns"
    )
    suggestions: list[str] = Field(
        default_factory=list,
        description="Suggestions for improvement"
    )
    novelty_check: str = Field(
        default="",
        description="Result of novelty check against literature"
    )
    similar_works: list[str] = Field(
        default_factory=list,
        description="Similar works found in literature"
    )
    recommendation: str = Field(
        default="",
        description="Overall recommendation (proceed, refine, drop)"
    )
    detailed_feedback: str = Field(
        default="",
        description="Detailed review feedback"
    )
    is_initial_review: bool = Field(
        default=True,
        description="Whether this is an initial (quick) or full review"
    )
    created_at: datetime = Field(default_factory=datetime.now)

    def calculate_overall_score(self) -> float:
        """Calculate weighted overall score from individual criteria."""
        weights = {
            "logical_consistency": 0.15,
            "novelty": 0.20,
            "testability": 0.15,
            "scientific_soundness": 0.20,
            "feasibility": 0.15,
            "relevance": 0.10,
            "clarity": 0.05,
        }
        total = sum(
            self.scores.get(criterion, 0) * weight
            for criterion, weight in weights.items()
        )
        self.overall_score = total
        return total


class HypothesisRanking(BaseModel):
    """Result of pairwise comparison/ranking between hypotheses."""

    id: str = Field(default_factory=lambda: f"rank_{datetime.now().strftime('%Y%m%d_%H%M%S_%f')}")
    hypothesis_a_id: str = Field(..., description="ID of first hypothesis")
    hypothesis_b_id: str = Field(..., description="ID of second hypothesis")
    winner_id: str = Field(..., description="ID of the winning hypothesis")
    comparison_rationale: str = Field(
        default="",
        description="Reasoning for the ranking decision"
    )
    score_delta: float = Field(
        default=32.0,
        description="Elo score change for this comparison"
    )
    comparison_criteria: list[str] = Field(
        default_factory=list,
        description="Criteria used for comparison"
    )
    created_at: datetime = Field(default_factory=datetime.now)


class HypothesisCluster(BaseModel):
    """A cluster of similar hypotheses identified by the Proximity agent."""

    id: str = Field(default_factory=lambda: f"cluster_{datetime.now().strftime('%Y%m%d_%H%M%S_%f')}")
    hypothesis_ids: list[str] = Field(
        default_factory=list,
        description="IDs of hypotheses in this cluster"
    )
    centroid_hypothesis_id: Optional[str] = Field(
        default=None,
        description="ID of the most representative hypothesis"
    )
    theme: str = Field(
        default="",
        description="Common theme or topic of the cluster"
    )
    similarity_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Average pairwise similarity within cluster"
    )
    merge_recommendation: Optional[str] = Field(
        default=None,
        description="Recommendation for merging similar hypotheses"
    )
    diversity_gap: Optional[str] = Field(
        default=None,
        description="Identified gap in hypothesis space"
    )
    created_at: datetime = Field(default_factory=datetime.now)


class HypothesisEvolution(BaseModel):
    """Record of hypothesis evolution/refinement."""

    id: str = Field(default_factory=lambda: f"evo_{datetime.now().strftime('%Y%m%d_%H%M%S_%f')}")
    original_hypothesis_id: str = Field(..., description="ID of the original hypothesis")
    evolved_hypothesis_id: str = Field(..., description="ID of the new evolved hypothesis")
    evolution_type: str = Field(
        default="refinement",
        description="Type of evolution (refinement, merge, simplification, expansion)"
    )
    changes_made: list[str] = Field(
        default_factory=list,
        description="List of changes made during evolution"
    )
    feedback_incorporated: list[str] = Field(
        default_factory=list,
        description="Review feedback that was addressed"
    )
    rationale: str = Field(
        default="",
        description="Reasoning for the evolution"
    )
    created_at: datetime = Field(default_factory=datetime.now)
